apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: tmmp-platform-chaos-engine
  namespace: tmmp-platform
spec:
  appinfo:
    appns: 'tmmp-platform'
    applabel: 'app=tmmp-command-handler'
    appkind: 'deployment'
  chaosServiceAccount: litmus-admin
  experiments:
    - name: pod-delete
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: '30'
            - name: CHAOS_INTERVAL
              value: '10'
            - name: FORCE
              value: 'true'
